AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  sam-go
  
  Sample SAM Template for sam-go

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 5
    MemorySize: 128

Resources:
  Service1Function:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: go1.x
    Properties:
      CodeUri: service1/
      Handler: bootstrap
      Runtime: provided.al2
      Architectures:
        - x86_64
      Events:
        CatchAll:
          Type: Api
          Properties:
            Path: /service1
            Method: GET
  Service2Function:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: go1.x
    Properties:
      CodeUri: service2/
      Handler: bootstrap
      Runtime: provided.al2
      Architectures:
        - x86_64
      Events:
        CatchAll:
          Type: Api
          Properties:
            Path: /service2
            Method: GET

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  Service1API:
    Description: "API Gateway endpoint URL for Prod environment for First Function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/service1/"
  Service1Function:
    Description: "First Lambda Function ARN"
    Value: !GetAtt Service1Function.Arn
  Service1FunctionIamRole:
    Description: "Implicit IAM Role created for Service1 function"
    Value: !GetAtt Service1FunctionRole.Arn
  Service2API:
    Description: "API Gateway endpoint URL for Prod environment for First Function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/service2/"
  Service2Function:
    Description: "First Lambda Function ARN"
    Value: !GetAtt Service2Function.Arn
  Service2FunctionIamRole:
    Description: "Implicit IAM Role created for Service2 function"
    Value: !GetAtt Service2FunctionRole.Arn